/**
 * Dossier de démonstration — données ENTIÈREMENT FICTIVES (organisme, SIRET, IBAN, personnes).
 * Sert aux tests et au jeu de données de démonstration. Aucune donnée réelle ne doit entrer ici.
 */
import type { AgregatDossier } from "./agregat";

export function dossierDeDemonstration(): AgregatDossier {
  return {
    dossier_reference: "ADF-2026-0001",
    sous_statut: "brouillon",
    mode_financement: "opco",
    organisme: {
      of_nom: "ORGANISME DÉMO FORMATION",
      of_forme_juridique: "SAS au capital de 1 000 €",
      of_adresse: "1 rue de l'Exemple, 68100 Mulhouse",
      of_siret: "00000000000000",
      of_nda_numero: "00 00 00000 00",
      of_dreets_region: "Grand Est",
      of_qualiopi_numero: "QUALIOPI-DEMO-0000",
      of_certification_complementaire_numero: "",
      of_representant_civilite: "Mme",
      of_representant_prenom: "Claire",
      of_representant_nom: "Exemple",
      of_email_pedagogie: "pedagogie@organisme-demo.example",
      of_email_comptabilite: "compta@organisme-demo.example",
      of_tribunal_competent: "tribunal de commerce de Mulhouse",
      of_iban: "FR00 0000 0000 0000 0000 0000 000",
      of_bic: "DEMOFRPP",
      of_banque_nom: "Banque Démo",
      of_tva_intracom: "",
      of_telephone: "03 00 00 00 00",
      formation_clause_subrogation:
        "Une demande de subrogation de paiement est déposée auprès de l'opérateur de compétences, qui règle directement l'organisme de formation à hauteur de sa prise en charge.",
      portage_commission_pourcentage: 25,
      tva_pourcentage: 0,
      delai_paiement_jours: 30,
    },
    entreprise: {
      entreprise_nom: "Menuiserie Dupont SARL",
      entreprise_nom_commercial: "Atelier Dupont",
      entreprise_adresse: "12 avenue des Artisans, 68200 Mulhouse",
      entreprise_siret: "11111111111111",
      entreprise_representant_civilite: "M.",
      entreprise_representant_prenom: "Jean",
      entreprise_representant_nom: "Dupont",
      entreprise_representant_telephone: "03 11 11 11 11",
      entreprise_representant_email: "jean.dupont@menuiserie-dupont.example",
    },
    formateur: {
      formateur_prenom: "Sophie",
      formateur_nom: "Lambert",
      formateur_email: "sophie.lambert@formatrice.example",
      formateur_telephone: "06 00 00 00 00",
      formateur_entreprise_nom: "SL Conseil EI",
      formateur_entreprise_adresse: "5 rue des Tilleuls, 67000 Strasbourg",
      formateur_entreprise_siret: "22222222222222",
      formateur_nda_numero: "00 11 22222 33",
      formateur_dreets_region: "Grand Est",
      formateur_iban: "FR11 1111 1111 1111 1111 1111 111",
      formateur_bic: "DEMOFRP2",
    },
    formation: {
      formation_titre: "Excel — tableaux croisés dynamiques et automatisation",
      formation_objectifs:
        "Construire et exploiter des tableaux croisés dynamiques.\nAutomatiser un reporting mensuel.\nFiabiliser ses fichiers par le contrôle des données.",
      formation_objectifs_atteints: "",
      formation_niveau: "Intermédiaire",
      formation_prerequis: "Maîtriser les fonctions de base d'Excel (saisie, mise en forme, formules simples).",
      formation_public_vise: "Assistants et gestionnaires administratifs.",
      formation_programme: "Jour 1 — Tableaux croisés dynamiques : construction, filtres, segments.\nJour 2 — Automatisation : requêtes, macros simples, contrôle des données.",
      formation_duree_heures_total: 14,
      formation_duree_jours: 2,
      formation_duree_heures_presentiel: 14,
      formation_duree_heures_distanciel: null,
      formation_modalite: "presentiel",
      formation_lieu_nom: "Menuiserie Dupont SARL",
      formation_lieu_adresse: "12 avenue des Artisans, 68200 Mulhouse",
      formation_lieu_siret: "11111111111111",
      formation_lien_visio: "",
      formation_date_debut: "2026-11-03",
      formation_date_fin: "2026-11-04",
      formation_opco: "OPCO Démo",
      formation_prix_unitaire_ht: 98_000,
      formation_prix_presentiel_ht: null,
      formateur_cout_horaire: null,
      signature_lieu: "Mulhouse",
    },
    stagiaires: [
      { id: "stg-1", nom: "Anne Martin", poste: "Assistante de gestion", email: "anne.martin@menuiserie-dupont.example", situation_handicap: "Non" },
      { id: "stg-2", nom: "Luc Petit", poste: "Chef d'atelier", email: "luc.petit@menuiserie-dupont.example", situation_handicap: "Non" },
    ],
    seances: [
      { id: "sea-1", date: "2026-11-03", heure_debut: "09:00", heure_fin: "12:30" },
      { id: "sea-2", date: "2026-11-03", heure_debut: "13:30", heure_fin: "17:00" },
      { id: "sea-3", date: "2026-11-04", heure_debut: "09:00", heure_fin: "12:30" },
      { id: "sea-4", date: "2026-11-04", heure_debut: "13:30", heure_fin: "17:00" },
    ],
    facture_of: {
      facture_of_numero: "FA-2026-0001",
      facture_of_date: "2026-11-05",
      facture_of_code_client: "C-0001",
      facture_of_numero_adherent: "ADH-0001",
      facture_of_acompte: null,
    },
    facture_formateur: { facture_formateur_numero: "FF-2026-0001", facture_formateur_date: "2026-11-05" },
    evaluations: {
      "stg-1": {
        recueil_date: "2026-10-01",
        positionnement_date: "2026-10-02",
        positionnement_ajustement: "Renforcer la partie « contrôle des données ».",
        evaluation_acquis_date: "2026-11-04",
        evaluation_acquis_score: 85,
        satisfaction_froid_date: "2027-02-04",
      },
      "stg-2": { recueil_date: "2026-10-01", positionnement_date: "2026-10-02", evaluation_acquis_date: "2026-11-04", evaluation_acquis_score: 60 },
    },
    heures_realisees: { "stg-1": 14, "stg-2": 10.5 },
    signature_date: "2026-10-10",
    attestation_date: "2026-11-05",
  };
}
